services:
  skeleton-app:
    depends_on:
      - functions-api
    image: node:22.12.0-slim
    ports:
      - 5173:5173
    working_dir: /app
    environment:
      - NODE_ENV=development
      - VITE_API_PROXY_TARGET=http://functions-api:3000
    volumes:
      - ./skeleton-app:/app
      - skeleton-app-node-modules:/app/node_modules
    command: /bin/sh -c "npm install && npm run dev"

  functions-api:
    image: node:18-slim
    ports:
      - 3000:3000
    working_dir: /app
    env_file:
      - functions-api/.env
    volumes:
      - ./functions-api:/app
      - functions-api-node-modules:/app/node_modules
    command: /bin/sh -c "npm install && npm run dev"

volumes:
  skeleton-app-node-modules:
  functions-api-node-modules:
