services:
  skeleton-app:
    image: node:20.12.1-slim
    ports:
      - 5173:5173
    working_dir: /app
    environment:
      - NODE_ENV=development
      - VITE_API_PROXY_TARGET=http://functions:3000
    volumes:
      - ./skeleton-app:/app
      - skeleton-app-node-modules:/app/node_modules
    command: /bin/sh -c "npm install && npm run dev"

  functions:
    image: node:18-slim
    ports:
      - 3000:3000
    working_dir: /app
    env_file:
      - functions/.env
    volumes:
      - ./functions:/app
      - functions-node-modules:/app/node_modules
    command: /bin/sh -c "npm install && npm run dev"

volumes:
  skeleton-app-node-modules:
  functions-node-modules:
