services:
  skeleton-app:
    image: node:20.12.1-slim
    ports:
      - 5173:5173
    working_dir: /app
    env_file:
      - .env
    volumes:
      - ./skeleton-app:/app
      - skeleton-app-node-modules:/app/node_modules
    command: /bin/sh -c "npm install && npm run dev"

volumes:
  skeleton-app-node-modules:
